//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Habit_Tracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habit
    {
        public System.Guid habitid { get; set; }
        public string habitname { get; set; }
        public string days_off { get; set; }
        public int current_streak { get; set; }
        public int longest_streak { get; set; }
        public int log_count { get; set; }
        public System.DateTime logs { get; set; }
        public System.Guid user_id { get; set; }
        public System.DateTime habitcreated_at { get; set; }
    }
}
